#!/usr/bin/env bash
#
# check-docs.sh -- throwaway reStructuredText build harness for Phase 00.
#
# Phase 00 writes evidence documents under docs/feasibility/. All project
# documentation must pass `sphinx-build -n -W` (nitpicky, warnings as errors).
# Phase 01 -- not Phase 00 -- owns the real Sphinx tree, so this script must
# never create docs/conf.py or .readthedocs.yaml. Instead it regenerates a
# disposable Sphinx source tree under _build/ (gitignored) on every run, so it
# can never go stale, and builds it.
#
# Usage:
#   scripts/feasibility/check-docs.sh              # every .rst in docs/feasibility/
#   scripts/feasibility/check-docs.sh FILE.rst     # just that one file
#
# The single-file form accepts any path, including a file outside the
# repository, which is what the harness's own negative test uses.
#
# Exit status:
#   0  sphinx-build succeeded AND the expected HTML files exist on disk
#   1  sphinx-build failed (a warning is an error under -W)
#   2  harness misuse or a broken environment (no venv, no documents, ...)
#   3  sphinx-build exited 0 but produced no/empty HTML -- exit code 0 proves
#      nothing, so this is checked rather than assumed
#
# Requires no network access once .venv exists.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd -- "${SCRIPT_DIR}/../.." && pwd)"

VENV="${PROJECT_ROOT}/.venv"
SPHINX_BUILD="${VENV}/bin/sphinx-build"
DOCS_DIR="${PROJECT_ROOT}/docs/feasibility"
BUILD_ROOT="${PROJECT_ROOT}/_build/docs-check"
SRC_DIR="${BUILD_ROOT}/src"
HTML_DIR="${BUILD_ROOT}/html"
DOCTREE_DIR="${BUILD_ROOT}/doctrees"
LOG_FILE="${BUILD_ROOT}/sphinx-build.log"

die() { printf 'check-docs.sh: %s\n' "$1" >&2; exit "${2:-2}"; }

if [ "$#" -gt 1 ]; then
    die "usage: check-docs.sh [FILE.rst]"
fi

if [ ! -x "${SPHINX_BUILD}" ]; then
    die "no sphinx-build at ${SPHINX_BUILD}.
Create the project virtualenv first (nothing may be installed on the host):
    python3 -m venv ${VENV}
    ${VENV}/bin/pip install sphinx"
fi

# --- collect the documents to check -----------------------------------------
# Auto-discovered, never hard-coded, so documents written by later work units
# are picked up without editing this script.

declare -a SRC_FILES=()   # absolute path of each source file
declare -a REL_PATHS=()   # path relative to the copy root, e.g. upstream-facts.rst

if [ "$#" -eq 1 ]; then
    single="$1"
    [ -f "${single}" ] || die "no such file: ${single}"
    case "${single}" in
        *.rst) : ;;
        *) die "not a .rst file: ${single}" ;;
    esac
    SRC_FILES+=("$(cd -- "$(dirname -- "${single}")" && pwd)/$(basename -- "${single}")")
    REL_PATHS+=("$(basename -- "${single}")")
    MODE_DESC="single file: ${single}"
else
    [ -d "${DOCS_DIR}" ] || die "no such directory: ${DOCS_DIR}"
    while IFS= read -r -d '' f; do
        SRC_FILES+=("${f}")
        REL_PATHS+=("${f#"${DOCS_DIR}"/}")
    done < <(find "${DOCS_DIR}" -type f -name '*.rst' -print0 | sort -z)
    MODE_DESC="all of ${DOCS_DIR}"
fi

if [ "${#SRC_FILES[@]}" -eq 0 ]; then
    die "no .rst files found (${MODE_DESC}); refusing to report success over an empty tree"
fi

# --- regenerate the throwaway source tree -----------------------------------

rm -rf -- "${SRC_DIR}" "${DOCTREE_DIR}" "${HTML_DIR}"
mkdir -p -- "${SRC_DIR}/feasibility" "${BUILD_ROOT}"

for i in "${!SRC_FILES[@]}"; do
    dest="${SRC_DIR}/feasibility/${REL_PATHS[$i]}"
    mkdir -p -- "$(dirname -- "${dest}")"
    cp -- "${SRC_FILES[$i]}" "${dest}"
done

cat > "${SRC_DIR}/conf.py" <<'CONF_EOF'
# Generated by scripts/feasibility/check-docs.sh. Throwaway: rewritten on every
# run and never committed. The real Sphinx configuration is Phase 01's to write
# at docs/conf.py, which this harness must not create.
project = "CometGUI feasibility evidence"
author = "CometGUI"
extensions = []
root_doc = "index"
exclude_patterns = []
templates_path = []
html_static_path = []
html_theme = "alabaster"
# No suppress_warnings, no nitpick_ignore: -n -W must bite.
CONF_EOF

# Generated master document: a toctree over every discovered document, so that
# nothing is left out of a toctree (which -W would turn into an error anyway).
{
    printf '%s\n' \
        '==============================================' \
        'CometGUI feasibility documents -- build check' \
        '=============================================='
    printf '\n'
    printf 'Generated by ``scripts/feasibility/check-docs.sh`` -- throwaway.\n\n'
    printf '.. toctree::\n   :maxdepth: 2\n\n'
    # index first when present, then the rest in sorted order.
    for rel in "${REL_PATHS[@]}"; do
        [ "${rel}" = "index.rst" ] && printf '   feasibility/index\n'
    done
    for rel in "${REL_PATHS[@]}"; do
        [ "${rel}" = "index.rst" ] && continue
        printf '   feasibility/%s\n' "${rel%.rst}"
    done
} > "${SRC_DIR}/index.rst"

# --- build -------------------------------------------------------------------

printf 'check-docs.sh: checking %s\n' "${MODE_DESC}"
printf 'check-docs.sh: %s document(s): %s\n' "${#REL_PATHS[@]}" "${REL_PATHS[*]}"
printf 'check-docs.sh: source tree %s\n' "${SRC_DIR}"
printf 'check-docs.sh: running %s -n -W -b html\n\n' "${SPHINX_BUILD}"

set +e
"${SPHINX_BUILD}" -n -W -b html -d "${DOCTREE_DIR}" "${SRC_DIR}" "${HTML_DIR}" 2>&1 | tee -- "${LOG_FILE}"
status="${PIPESTATUS[0]}"
set -e

printf '\n'

if [ "${status}" -ne 0 ]; then
    printf 'check-docs.sh: FAILED -- sphinx-build exited %s (warnings are errors under -W).\n' "${status}" >&2
    printf 'check-docs.sh: full output kept at %s\n' "${LOG_FILE}" >&2
    exit 1
fi

# --- exit code 0 proves nothing: verify the HTML actually exists -------------

missing=0
for rel in "${REL_PATHS[@]}"; do
    page="${HTML_DIR}/feasibility/${rel%.rst}.html"
    if [ ! -s "${page}" ]; then
        printf 'check-docs.sh: expected HTML missing or empty: %s\n' "${page}" >&2
        missing=1
    fi
done
if [ ! -s "${HTML_DIR}/index.html" ]; then
    printf 'check-docs.sh: expected HTML missing or empty: %s\n' "${HTML_DIR}/index.html" >&2
    missing=1
fi
if [ "${missing}" -ne 0 ]; then
    printf 'check-docs.sh: FAILED -- sphinx-build exited 0 but produced no usable HTML.\n' >&2
    exit 3
fi

pages="$(find "${HTML_DIR}" -type f -name '*.html' | wc -l | tr -d ' ')"
printf 'check-docs.sh: OK -- %s HTML page(s) written under %s\n' "${pages}" "${HTML_DIR}"
printf 'check-docs.sh: landing page %s\n' "${HTML_DIR}/feasibility/index.html"
printf 'check-docs.sh: sphinx output kept at %s\n' "${LOG_FILE}"
exit 0
