#!/usr/bin/env python3
"""Render the tool-artefact documentation fragments from ``manifests/tools.json``.

Phase 05 unit 11. Two pages of the published tree state facts that also live in
the tool artefact manifest -- which platforms carry which build, how large each
download is, which capability each row declares and on what evidence, and every
URL, size, digest and licence the installer pins. Typing those into a page
creates a second copy of the manifest that nothing keeps in step, and this
project has already paid twice for a second copy of something.

So the fragments are **generated during the documentation build**, exactly as
the traceability report (``R-DOC-03``) is: ``docs/conf.py`` calls
:func:`generate` from a ``builder-inited`` handler, before Sphinx reads the
source tree, and the pages pull the result in with ``.. include::``. There is no
committed copy of the tables to drift, and a manifest the generator refuses is a
**documentation build failure** rather than a stale page nobody re-reads.

The generator is also runnable on its own, which is how its reaction to its
input is demonstrated::

    python3 scripts/toolmatrix.py --check
    python3 scripts/toolmatrix.py --manifest /tmp/edited.json --out-dir /tmp/out

Standard library only, deliberately: ``docs/requirements.txt`` is what Read the
Docs installs, and a generator that added to it would make the published build
depend on a package the gate does not pin.

Exit status of the command-line form:

==  =============================================================
0   the manifest validated, and (unless ``--check``) was rendered
1   the manifest was rejected -- the message names the field
2   misuse, or no manifest where one was expected
==  =============================================================
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

#: Where the manifest lives, relative to the repository root. One file, shipped
#: once: ``cometgui-install`` ships this same path into its jar through a
#: ``<resource>`` element, so a second copy here would be a third copy overall.
MANIFEST_RELATIVE_PATH = Path("manifests") / "tools.json"

#: Where the fragments are written, relative to the documentation source root.
#: Gitignored: nothing generated is committed.
OUTPUT_RELATIVE_DIR = Path("_generated")

#: The per-platform matrix, included by ``docs/platform_support.rst``.
PLATFORM_MATRIX_FILE = "tool-platform-matrix.rsti"

#: The artefact provenance table, included by ``docs/developer/tool_registry.rst``.
ARTEFACT_PROVENANCE_FILE = "tool-artefact-provenance.rsti"

#: The platforms this project names. An artefact for anything else is refused
#: rather than dropped: a platform the manifest gains and the documentation
#: silently omits is the drift these fragments exist to prevent.
KNOWN_PLATFORMS = (
    "linux-x86-64",
    "linux-aarch64",
    "macos-x86-64",
    "macos-aarch64",
    "windows-x86-64",
)

#: The evidence values ``org.cometgui.domain.tools.CapabilityEvidence`` defines.
#: A fourth one appearing here without this generator knowing it is refused.
KNOWN_EVIDENCE = (
    "observed-by-execution",
    "inferred-from-artefact-bytes",
    "unverified",
)

#: Fields every artefact record must carry, in the order ``R-TOOL-01`` and
#: ``R-TOOL-03`` name them. A record missing one is rejected **naming the
#: field**, because "the table came out short" is not a diagnosis.
REQUIRED_ARTEFACT_FIELDS = (
    "tool",
    "version",
    "releaseTag",
    "os",
    "arch",
    "kind",
    "url",
    "sizeBytes",
    "sha256",
    "md5",
    "licence",
    "companions",
    "capabilities",
    "advisories",
    "minimumHostRequirements",
    "minimumCometGuiVersion",
)

REQUIRED_COMPANION_FIELDS = ("id", "kind", "url", "sizeBytes", "sha256", "md5", "members")

REQUIRED_COMPANION_MEMBER_FIELDS = ("path", "sizeBytes", "sha256", "md5", "installedPath")

#: The four words this project does not use of a binary nobody has run. The
#: word boundary is what keeps ``unverified`` -- a legitimate evidence value --
#: from matching. ``cometgui-install``'s ``ShippedManifestTest`` enforces the
#: same rule over the manifest text; this enforces it over what reaches a page,
#: which is where a reader would act on it.
BANNED_CLAIM_WORDS = re.compile(r"\b(verified|confirmed|proven|tested)\b", re.IGNORECASE)

_GENERATED_HEADER = (
    ".. Generated by scripts/toolmatrix.py from {manifest} during the\n"
    "   documentation build (see docs/conf.py). Not committed and never edited by\n"
    "   hand: a table typed beside a manifest is a second copy of the manifest.\n"
    "   To change what this says, change the manifest or the generator.\n"
)


class ToolMatrixError(Exception):
    """The manifest was rejected, or the rendered text broke a rule.

    Carried out of :func:`generate` so that ``docs/conf.py`` can turn it into a
    Sphinx ``ExtensionError`` and fail the documentation build with it.
    """


# --------------------------------------------------------------------------
# Reading and validating
# --------------------------------------------------------------------------


def manifest_path(root: Path) -> Path:
    """Return the manifest path under ``root``."""
    return Path(root) / MANIFEST_RELATIVE_PATH


def load(path: Path) -> dict:
    """Read and validate one manifest.

    :param path: the manifest file.
    :returns: the parsed manifest, with a ``sha256`` and ``path`` recorded under
        the private keys ``_digest`` and ``_path`` for the fragments to quote.
    :raises ToolMatrixError: if the file is missing, is not JSON, or breaks any
        rule below. Every message names the record and the field.
    """
    path = Path(path)
    try:
        raw = path.read_bytes()
    except OSError as error:
        raise ToolMatrixError(f"cannot read the tool artefact manifest at {path}: {error}") from None
    try:
        manifest = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise ToolMatrixError(f"{path} is not valid UTF-8 JSON: {error}") from None
    if not isinstance(manifest, dict):
        raise ToolMatrixError(f"{path}: the manifest must be a JSON object, not {_kind(manifest)}")
    artefacts = manifest.get("artefacts")
    if not isinstance(artefacts, list):
        raise ToolMatrixError(
            f"{path}: the manifest must carry an \"artefacts\" array; "
            f"found {_kind(artefacts)}"
        )
    if not artefacts:
        raise ToolMatrixError(
            f"{path}: the manifest carries no artefacts. Rendering an empty platform "
            "matrix would say this project manages no tools, which is a claim, not an "
            "absence."
        )
    for index, artefact in enumerate(artefacts):
        _validate_artefact(path, index, artefact)
    manifest["_digest"] = hashlib.sha256(raw).hexdigest()
    manifest["_path"] = path
    return manifest


def _kind(value) -> str:
    """Name a JSON value's type for a diagnostic."""
    if value is None:
        return "nothing"
    return {
        dict: "an object",
        list: "an array",
        str: "a string",
        bool: "a boolean",
        int: "a number",
        float: "a number",
    }.get(type(value), type(value).__name__)


def _where(index: int, artefact) -> str:
    """Name a record for a diagnostic, by identity where it has one."""
    if isinstance(artefact, dict):
        tool = artefact.get("tool")
        version = artefact.get("version")
        platform = _platform_of_or_none(artefact)
        named = " ".join(str(part) for part in (tool, version, platform) if part)
        if named:
            return f"artefacts[{index}] ({named})"
    return f"artefacts[{index}]"


def _platform_of_or_none(artefact: dict):
    """The platform identifier of a record, where both halves are strings."""
    host_os = artefact.get("os")
    arch = artefact.get("arch")
    if isinstance(host_os, str) and isinstance(arch, str):
        return f"{host_os}-{arch}"
    return None


def _validate_artefact(path: Path, index: int, artefact) -> None:
    """Refuse one artefact record that cannot be rendered honestly."""
    where = _where(index, artefact)
    if not isinstance(artefact, dict):
        raise ToolMatrixError(f"{path}: {where} must be an object, not {_kind(artefact)}")
    for field in REQUIRED_ARTEFACT_FIELDS:
        if field not in artefact:
            raise ToolMatrixError(
                f"{path}: {where} is missing the required field \"{field}\". Every field "
                "R-TOOL-01 and R-TOOL-03 name is required, because the documentation "
                "table is built from them and a blank cell reads as a fact."
            )
    platform = _platform_of_or_none(artefact)
    if platform is None:
        raise ToolMatrixError(
            f"{path}: {where} has a non-string \"os\" or \"arch\"; the platform identifier "
            "is os-arch and both halves are required."
        )
    if platform not in KNOWN_PLATFORMS:
        raise ToolMatrixError(
            f"{path}: {where} names the platform \"{platform}\", which this generator does "
            f"not know. The platforms it renders are {', '.join(KNOWN_PLATFORMS)}. A "
            "platform added to the manifest must be added here too -- a row this page "
            "quietly omits is exactly the drift a generated page exists to prevent."
        )
    url = artefact["url"]
    if not isinstance(url, str) or not url.startswith("https://"):
        raise ToolMatrixError(
            f"{path}: {where} has the download URL {url!r}. D-008 downloads every managed "
            "tool by pinned https URL; a manifest row that is not https is refused here "
            "rather than published as one."
        )
    for field in ("sizeBytes",):
        value = artefact[field]
        if not isinstance(value, int) or isinstance(value, bool) or value <= 0:
            raise ToolMatrixError(
                f"{path}: {where} has \"{field}\" = {value!r}; a download size is a positive "
                "number of bytes, and it is the figure a user reads before starting a "
                "transfer."
            )
    _validate_digest(path, where, "sha256", artefact["sha256"], 64)
    _validate_digest(path, where, "md5", artefact["md5"], 32)
    licence = artefact["licence"]
    if not isinstance(licence, dict) or not isinstance(licence.get("spdx"), str):
        raise ToolMatrixError(
            f"{path}: {where} has no \"licence.spdx\"; R-TOOL-01 requires licence metadata "
            "on every record and the provenance table prints it."
        )
    _validate_capabilities(path, where, artefact["capabilities"])
    _validate_companions(path, where, artefact["companions"])
    requirements = artefact["minimumHostRequirements"]
    if not isinstance(requirements, dict):
        raise ToolMatrixError(
            f"{path}: {where} has \"minimumHostRequirements\" = {_kind(requirements)}; "
            "R-TOOL-03 requires the object, with its fields null where there is no floor."
        )
    libraries = requirements.get("requiredHostLibraries")
    if not isinstance(libraries, list):
        raise ToolMatrixError(
            f"{path}: {where} has \"minimumHostRequirements.requiredHostLibraries\" = "
            f"{_kind(libraries)}; it is a list, empty where the artefact needs nothing."
        )


def _validate_digest(path: Path, where: str, field: str, value, length: int) -> None:
    """Refuse a digest that is not lower-case hex of the right length."""
    if not isinstance(value, str) or len(value) != length or not re.fullmatch(r"[0-9a-f]+", value):
        raise ToolMatrixError(
            f"{path}: {where} has \"{field}\" = {value!r}; expected {length} lower-case hex "
            "characters. The provenance table prints this digest and a reader checks a "
            "download against it."
        )


def _validate_capabilities(path: Path, where: str, capabilities) -> None:
    """Refuse a capability claim with no evidence, or with evidence nobody defined."""
    if not isinstance(capabilities, list):
        raise ToolMatrixError(
            f"{path}: {where} has \"capabilities\" = {_kind(capabilities)}; it is a list, "
            "empty where the build declares nothing."
        )
    for position, capability in enumerate(capabilities):
        at = f"{where} capabilities[{position}]"
        if not isinstance(capability, dict):
            raise ToolMatrixError(f"{path}: {at} must be an object, not {_kind(capability)}")
        name = capability.get("capability")
        evidence = capability.get("evidence")
        note = capability.get("note")
        if not isinstance(name, str) or not name:
            raise ToolMatrixError(f"{path}: {at} has no \"capability\" name")
        if evidence not in KNOWN_EVIDENCE:
            raise ToolMatrixError(
                f"{path}: {at} declares {name} on the evidence {evidence!r}. Every "
                "capability carries how it was established, and the values are "
                f"{', '.join(KNOWN_EVIDENCE)}. A claim this generator cannot attribute is "
                "refused rather than printed bare."
            )
        if not isinstance(note, str) or not note.strip():
            raise ToolMatrixError(
                f"{path}: {at} declares {name} with no note. The note is the only field "
                "recording who established the claim and what they saw."
            )


def _validate_companions(path: Path, where: str, companions) -> None:
    """Refuse a companion record the provenance table could not print in full."""
    if not isinstance(companions, list):
        raise ToolMatrixError(
            f"{path}: {where} has \"companions\" = {_kind(companions)}; it is a list, empty "
            "where the artefact has none."
        )
    for position, companion in enumerate(companions):
        at = f"{where} companions[{position}]"
        if not isinstance(companion, dict):
            raise ToolMatrixError(f"{path}: {at} must be an object, not {_kind(companion)}")
        for field in REQUIRED_COMPANION_FIELDS:
            if field not in companion:
                raise ToolMatrixError(
                    f"{path}: {at} is missing the required field \"{field}\". A companion is "
                    "a second download installed atomically with the binary (R-TOOL-02) and "
                    "it is part of the transfer a user is shown."
                )
        _validate_digest(path, at, "sha256", companion["sha256"], 64)
        _validate_digest(path, at, "md5", companion["md5"], 32)
        members = companion["members"]
        if not isinstance(members, list) or not members:
            raise ToolMatrixError(
                f"{path}: {at} has no \"members\"; a companion archive is fetched for the "
                "files it carries, and the record names them."
            )
        for member_position, member in enumerate(members):
            member_at = f"{at} members[{member_position}]"
            if not isinstance(member, dict):
                raise ToolMatrixError(f"{path}: {member_at} must be an object")
            for field in REQUIRED_COMPANION_MEMBER_FIELDS:
                if field not in member:
                    raise ToolMatrixError(
                        f"{path}: {member_at} is missing the required field \"{field}\"."
                    )
            _validate_digest(path, member_at, "sha256", member["sha256"], 64)


# --------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------


def _bytes_text(value: int) -> str:
    """A byte count with thin-space grouping, so a nine-digit figure is readable."""
    return f"{value:,}".replace(",", " ")


def _platform_of(artefact: dict) -> str:
    return f"{artefact['os']}-{artefact['arch']}"


def _release_of(artefact: dict) -> str:
    return f"{artefact['tool']} {artefact['version']}"


def _capability_text(artefact: dict) -> str:
    """Every declared capability of one record, each with its evidence."""
    capabilities = artefact["capabilities"]
    if not capabilities:
        return "none declared"
    return ", ".join(
        f"``{item['capability']}`` ({item['evidence']})" for item in capabilities
    )


def _host_requirement_text(artefact: dict) -> str:
    """One record's minimum host requirements, in the words R-TOOL-03 asks for."""
    requirements = artefact["minimumHostRequirements"]
    parts = []
    if requirements.get("glibc"):
        parts.append(f"glibc {requirements['glibc']}")
    if requirements.get("glibcxx"):
        parts.append(f"GLIBCXX {requirements['glibcxx']}")
    if requirements.get("macos"):
        parts.append(f"macOS {requirements['macos']}")
    libraries = requirements.get("requiredHostLibraries") or []
    if libraries:
        parts.append(", ".join(f"``{name}``" for name in libraries))
    return "; ".join(parts) if parts else "none declared"


def _whole_download_bytes(artefact: dict) -> int:
    """The transfer a row costs: the artefact plus every companion it names.

    The same sum ``ManagedToolManager.wholeDownloadOf`` computes for the Tool
    Manager. A figure that named only the artefact would be three times small
    for Percolator on Linux, which fetches a portable zip and the package its
    two XSD companions come out of.
    """
    return int(artefact["sizeBytes"]) + sum(
        int(companion["sizeBytes"]) for companion in artefact["companions"]
    )


def _list_table(caption: str, widths, header, rows) -> str:
    """Render a reST ``list-table``. Cells may be multi-line."""
    out = [f".. list-table:: {caption}", "   :header-rows: 1", f"   :widths: {widths}", ""]
    for row in (header, *rows):
        first = True
        for cell in row:
            lines = str(cell).split("\n")
            marker = "   * - " if first else "     - "
            out.append(marker + lines[0])
            for line in lines[1:]:
                out.append("       " + line if line else "")
            first = False
    out.append("")
    return "\n".join(out)


def render_platform_matrix(manifest: dict) -> str:
    """Render the per-platform artefact matrix included by ``platform_support.rst``."""
    artefacts = manifest["artefacts"]
    releases = []
    for artefact in artefacts:
        release = _release_of(artefact)
        if release not in releases:
            releases.append(release)
    by_release_platform = {
        (_release_of(artefact), _platform_of(artefact)): artefact for artefact in artefacts
    }

    matrix_rows = []
    for release in releases:
        cells = [f"``{release}``"]
        for platform in KNOWN_PLATFORMS:
            artefact = by_release_platform.get((release, platform))
            if artefact is None:
                cells.append("not published")
            else:
                cells.append(
                    f"``{artefact['kind']}``\n\n{_bytes_text(_whole_download_bytes(artefact))} B"
                )
        matrix_rows.append(cells)

    percolator_rows = []
    for platform in KNOWN_PLATFORMS:
        rows_here = [
            artefact
            for artefact in artefacts
            if artefact["tool"] == "percolator" and _platform_of(artefact) == platform
        ]
        if not rows_here:
            percolator_rows.append(
                [
                    f"``{platform}``",
                    "no managed build",
                    "--",
                    "--",
                    "--",
                ]
            )
            continue
        for artefact in rows_here:
            xml = [
                item
                for item in artefact["capabilities"]
                if item["capability"] == "XML_OUTPUT"
            ]
            if xml:
                declared = f"declared, evidence {xml[0]['evidence']}"
            else:
                declared = "not declared"
            percolator_rows.append(
                [
                    f"``{platform}``",
                    artefact["version"],
                    f"``{artefact['kind']}`` from ``{artefact['releaseTag']}``",
                    declared,
                    _host_requirement_text(artefact),
                ]
            )

    text = [
        _GENERATED_HEADER.format(manifest="manifests/tools.json"),
        "",
        f"Rendered from ``manifests/tools.json`` (SHA-256 ``{manifest['_digest']}``),",
        f"which carries {len(artefacts)} artefact records across "
        f"{len(KNOWN_PLATFORMS)} platforms.",
        "",
        _list_table(
            "Managed tool builds the manifest publishes, by platform. The figure is the "
            "whole transfer -- the artefact plus every companion the record names -- not "
            "what lands on disk.",
            "20 16 16 16 16 16",
            ["Release", *(f"``{platform}``" for platform in KNOWN_PLATFORMS)],
            matrix_rows,
        ),
        _list_table(
            "Percolator, per platform: what is published, what the record declares about "
            "XML output and on what evidence, and what the host must satisfy. The declared "
            "capability is what the manifest carries before an install; R-TOOL-07's probe "
            "decides on the host and overrides it.",
            "16 10 26 26 22",
            [
                "Platform",
                "Version",
                "Artefact",
                "``XML_OUTPUT``",
                "Minimum host requirements",
            ],
            percolator_rows,
        ),
        _list_table(
            "Every artefact record, with the capabilities it declares and the evidence "
            "behind each claim.",
            "14 12 16 12 46",
            ["Platform", "Tool", "Version", "Kind", "Declared capabilities"],
            [
                [
                    f"``{_platform_of(artefact)}``",
                    artefact["tool"],
                    artefact["version"],
                    f"``{artefact['kind']}``",
                    _capability_text(artefact),
                ]
                for artefact in sorted(
                    artefacts, key=lambda a: (_platform_of(a), a["tool"], a["version"])
                )
            ],
        ),
    ]
    return "\n".join(text) + "\n"


def render_artefact_provenance(manifest: dict) -> str:
    """Render the artefact provenance table included by ``developer/tool_registry.rst``."""
    artefacts = manifest["artefacts"]
    rows = []
    companion_count = 0
    for artefact in artefacts:
        rows.append(
            [
                f"{_release_of(artefact)}\n\n``{_platform_of(artefact)}``, "
                f"``{artefact['releaseTag']}``\n\n{artefact['url']}",
                f"``{artefact['kind']}``",
                _bytes_text(int(artefact["sizeBytes"])),
                f"``{artefact['sha256']}``",
                artefact["licence"]["spdx"],
            ]
        )
        for companion in artefact["companions"]:
            companion_count += 1
            members = "\n\n".join(
                f"``{member['installedPath']}`` "
                f"({_bytes_text(int(member['sizeBytes']))} B, ``{member['sha256']}``)"
                for member in companion["members"]
            )
            rows.append(
                [
                    f"companion of {_release_of(artefact)} "
                    f"``{_platform_of(artefact)}``\n\n``{companion['id']}``\n\n"
                    f"{companion['url']}\n\n{members}",
                    f"``{companion['kind']}``",
                    _bytes_text(int(companion["sizeBytes"])),
                    f"``{companion['sha256']}``",
                    artefact["licence"]["spdx"],
                ]
            )

    text = [
        _GENERATED_HEADER.format(manifest="manifests/tools.json"),
        "",
        f"Rendered from ``manifests/tools.json`` (SHA-256 ``{manifest['_digest']}``):",
        f"{len(artefacts)} artefact records and {companion_count} companion archives.",
        "Every digest below is the one the installer requires before the bytes are",
        "unpacked or run, and the one a reader can re-derive from the download.",
        "",
        _list_table(
            "Artefact provenance: what is fetched, from where, how large it is, the "
            "SHA-256 the installer pins, and the licence the record carries. Companion "
            "archives are listed under the artefact they are fetched for, with the files "
            "taken out of them.",
            "34 12 10 30 12",
            ["Artefact and download URL", "Kind", "Bytes", "SHA-256", "Licence"],
            rows,
        ),
    ]
    return "\n".join(text) + "\n"


def _check_claim_words(name: str, text: str) -> None:
    """Refuse rendered text that claims a capability in words this project reserves."""
    for number, line in enumerate(text.splitlines(), start=1):
        match = BANNED_CLAIM_WORDS.search(line)
        if match:
            raise ToolMatrixError(
                f"{name} line {number} uses the word \"{match.group(0)}\": "
                f"{line.strip()!r}. No macOS binary has ever been executed anywhere in this "
                "project and one Windows binary has been executed once on one hosted "
                "runner, so verified/confirmed/proven/tested are not words this "
                "documentation uses of a build. Say what was observed, and where."
            )


# --------------------------------------------------------------------------
# The entry point docs/conf.py calls
# --------------------------------------------------------------------------


def generate(root: Path, out_dir: Path, manifest_file: Path = None) -> dict:
    """Validate the manifest and write both fragments.

    :param root: the repository root, used to find the manifest.
    :param out_dir: the directory to write the fragments into; created if absent.
    :param manifest_file: an explicit manifest, for the command-line form.
    :returns: a summary -- the files written, the record counts and the digest.
    :raises ToolMatrixError: if the manifest is rejected, if the rendered text
        breaks the claim-word rule, or if a file that was reported as written is
        missing or empty. Exit code 0 proves nothing, so the written files are
        read back before this returns.
    """
    source = Path(manifest_file) if manifest_file else manifest_path(root)
    manifest = load(source)

    fragments = {
        PLATFORM_MATRIX_FILE: render_platform_matrix(manifest),
        ARTEFACT_PROVENANCE_FILE: render_artefact_provenance(manifest),
    }
    for name, text in fragments.items():
        _check_claim_words(name, text)

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for name, text in fragments.items():
        target = out_dir / name
        target.write_text(text, encoding="utf-8")
        if not target.is_file() or target.stat().st_size == 0:
            raise ToolMatrixError(
                f"the generator reported writing {target} but the file is missing or empty."
            )
        written.append(target)

    companions = sum(len(artefact["companions"]) for artefact in manifest["artefacts"])
    return {
        "manifest": source,
        "digest": manifest["_digest"],
        "artefacts": len(manifest["artefacts"]),
        "companions": companions,
        "platforms": len(KNOWN_PLATFORMS),
        "written": written,
    }


def _main(argv) -> int:
    parser = argparse.ArgumentParser(
        prog="toolmatrix.py",
        description=(
            "Render the tool-artefact documentation fragments from manifests/tools.json. "
            "The documentation build calls generate() directly; this form exists to run "
            "the generator over an edited manifest and see the tables change."
        ),
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
        help="repository root (default: the one holding this script)",
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=None,
        help="an explicit manifest file, instead of <root>/manifests/tools.json",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=None,
        help="where to write the fragments (default: <root>/docs/_generated)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate the manifest and render, but write nothing",
    )
    args = parser.parse_args(argv)

    out_dir = args.out_dir or (args.root / "docs" / OUTPUT_RELATIVE_DIR)
    try:
        if args.check:
            source = args.manifest or manifest_path(args.root)
            manifest = load(source)
            for name, text in (
                (PLATFORM_MATRIX_FILE, render_platform_matrix(manifest)),
                (ARTEFACT_PROVENANCE_FILE, render_artefact_provenance(manifest)),
            ):
                _check_claim_words(name, text)
            companions = sum(len(a["companions"]) for a in manifest["artefacts"])
            print(
                f"toolmatrix: {source} validates -- {len(manifest['artefacts'])} artefact "
                f"record(s), {companions} companion archive(s), sha256 {manifest['_digest']}"
            )
            return 0
        summary = generate(args.root, out_dir, args.manifest)
    except ToolMatrixError as error:
        print(f"toolmatrix: {error}", file=sys.stderr)
        return 1
    for target in summary["written"]:
        print(f"toolmatrix: wrote {target} ({target.stat().st_size} bytes)")
    print(
        f"toolmatrix: from {summary['manifest']} -- {summary['artefacts']} artefact "
        f"record(s), {summary['companions']} companion archive(s), "
        f"{summary['platforms']} platform(s), sha256 {summary['digest']}"
    )
    return 0


if __name__ == "__main__":  # pragma: no cover - command-line form
    sys.exit(_main(sys.argv[1:]))
